### ISSUE TITLE
In tables, a value of 0 for the slot gets dropped

### ISSUE THREAD

**Issue by Epithumia** [ajomuch92/vue-tailwind-elements#1]
Using the last example from the [docs](https://vue-tailwind-elements.netlify.app/#/table):

```js
<te-table :items="items" :headers="headers" show-row-num :item-per-page="3">
  <template v-slot:handle="{value}">
    <te-badge type="info" :text="value" />
  </template>
</te-table>
```

If items.handle is 0, then "undefined" is passed instead of 0 (I guess because `item[header.field] || item[header]` becomes `undefined||0` which stays undefined.

**Comment by ajomuch92** [comment]
Thanks for reporting this bug @Epithumia. I will check it and release a new version when it's done

**Comment by ajomuch92** [comment]
A new version was released, the issue is closed @Epithumia
