### ISSUE TITLE
Optional Slot for Accordion Header

### ISSUE THREAD

**Issue by wug-ge** [ajomuch92/vue-tailwind-elements#3]
Hey,

thanks for this great package first!

I'm using a Te-Accordion, but I don't only want to have a single Button as a header. (Rather a whole clickable line with a grid)

Is it possible to overwrite the button with a slot if needed so I can inject HTML into the header?

**Comment by ajomuch92** [comment]
Thanks for your suggestion @wug-ge, I added a new slots for header on TeAccordion component, I will release a new version with this new feature
