### ISSUE TITLE
Support first item to be open (or pushing open items as a prop) in teAccordion

### ISSUE THREAD

**Issue by wug-ge** [ajomuch92/vue-tailwind-elements#8]
Hi!
Thanks for the useful library first of all!

It would be very useful if I could push itemsOpened as a Prop to teAccordion.vue.
In my case, I'd like the first element of the Accordion to be open by default.

I can also try tinkering my way through it if you accept pull requests?

**Comment by ajomuch92** [comment]
@wug-ge Yes, go ahead, open a PR and I will check it
